spring:
  application:
    name: wu-ai-agent
  ai:
    dashscope:
      #api-key: sk-be82004ba1c84643b26be4ba97727284
      #chat:
      #  options:
      #    model: qwen-flash
      api-key: sk-affc42369fa14b65b28b84469c3a56a7
      chat:
        options:
            model: tingwu-service-insights
